language: python
python:
  - "3.8"
  - "3.9"
  - "3.9-dev"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install cython
  - pip install pyasn1
  - pip install scrapy
install:
  - python setup.py -q install
# command to run tests
script:
  - python -m unittest tests.test_api.TestCrawlTimeRange
branches:
  only:
    - main