language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
# command to install dependencies
before_install:
  - python --version
  - pip install -U pip
  - pip install cython
install:
  - python setup.py -q install
# command to run tests
script:
  - pytest
branches:
  only:
    - main