sudo: required
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"
# command to install dependencies
before_install:
  - python --version
  - sudo pip install -U pip
  - sudo pip install -U openpyxl
  - sudo pip install -U pandas
  - sudo pip install -U scrapy
install:
  - python setup.py -q install
# command to run tests
script:
  - pytest
branches:
  only:
    - main